"use client";

import { Check, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { cn } from "@/lib/utils";

/**
 * Looping visual replay of a run for the landing hero: prompt typed →
 * synthetic images appear → verified boxes draw on → training → model ready.
 * The three tiles are REAL SDXL outputs from the showcase dataset
 * (public/landing/gen-*.jpg) with their REAL Critic-verified YOLO boxes.
 */
const PROMPT = "a yellow forklift moving pallets in a busy warehouse";

// Normalized cx/cy/w/h straight from the dataset records (ds_0006).
type Box = { label: string; color: string; cx: number; cy: number; w: number; h: number };
const TILES: { src: string; boxes: Box[] }[] = [
  {
    src: "/landing/gen-3.jpg",
    boxes: [
      { label: "forklift", color: "#d97706", cx: 0.416, cy: 0.5438, w: 0.3675, h: 0.6799 },
      { label: "worker", color: "#65a30d", cx: 0.3081, cy: 0.5382, w: 0.2239, h: 0.5901 },
    ],
  },
  {
    src: "/landing/gen-1.jpg",
    boxes: [
      { label: "forklift", color: "#d97706", cx: 0.6633, cy: 0.5346, w: 0.165, h: 0.284 },
    ],
  },
  {
    src: "/landing/gen-2.jpg",
    boxes: [
      { label: "pallet", color: "#0284c7", cx: 0.6112, cy: 0.8355, w: 0.4862, h: 0.1004 },
    ],
  },
];

// One 250 ms tick drives the whole timeline; everything derives from `t`.
const TYPE_END = 11;
const TILE_AT = [14, 17, 20];
const BOX_AT = [24, 26, 28];
const TRAIN_START = 31;
const TRAIN_END = 45;
const DONE_AT = 46;
const LOOP_AT = 62;

export function HeroVisual() {
  const [t, setT] = useState(0);

  useEffect(() => {
    const id = setInterval(() => setT((v) => (v >= LOOP_AT ? 0 : v + 1)), 250);
    return () => clearInterval(id);
  }, []);

  const typed = PROMPT.slice(0, Math.ceil((PROMPT.length * Math.min(t, TYPE_END)) / TYPE_END));
  const expanded = t > TYPE_END + 1;
  const training = t >= TRAIN_START && t < DONE_AT;
  const done = t >= DONE_AT;
  const progress = Math.min(1, Math.max(0, (t - TRAIN_START) / (TRAIN_END - TRAIN_START)));

  const status = done
    ? "model_0014 ready · mAP50 0.85 · exported .pt / ONNX"
    : training
      ? `Training YOLOv10 · epoch ${Math.max(1, Math.round(progress * 60))}/60`
      : t >= BOX_AT[0]
        ? "Critic verifying every label — geometry + VLM"
        : t >= TILE_AT[0]
          ? "Synthesizing scenarios (SDXL)"
          : expanded
            ? "48 domain-randomized scenarios queued"
            : "Describe what the model should detect";

  return (
    <div className="relative">
      <div aria-hidden className="absolute -inset-8 rounded-[3rem] bg-primary/15 blur-3xl" />
      <div className="relative space-y-5">
        {/* prompt bar */}
        <div className="mx-auto flex max-w-xl items-center gap-3 rounded-full border bg-card px-5 py-3 shadow-xl">
          <Sparkles className="size-4 shrink-0 text-primary" />
          <p className="truncate text-sm">
            {typed}
            {!expanded && <span className="animate-pulse text-muted-foreground">▍</span>}
          </p>
          <span
            className={cn(
              "ml-auto shrink-0 rounded-full border border-primary/40 bg-primary/10 px-2.5 py-0.5 text-[11px] text-primary transition-opacity duration-500",
              expanded ? "opacity-100" : "opacity-0",
            )}
          >
            → 48 scenarios
          </span>
        </div>

        {/* generated tiles with verified boxes */}
        <div className="grid grid-cols-3 gap-3 sm:gap-4">
          {TILES.map((tile, i) => {
            const shown = t >= TILE_AT[i];
            const boxed = t >= BOX_AT[i];
            return (
              <div
                key={tile.src}
                className={cn(
                  "relative aspect-square overflow-hidden rounded-2xl border shadow-2xl transition-all duration-700",
                  shown
                    ? "translate-y-0 border-white/15 opacity-100"
                    : "translate-y-2 border-dashed border-white/10 bg-white/[0.03] opacity-90",
                )}
              >
                {/* eslint-disable-next-line @next/next/no-img-element -- static marketing asset, no optimization needed */}
                <img
                  src={tile.src}
                  alt="Synthetic training image generated by the swarm"
                  className={cn(
                    "size-full object-cover transition-all duration-700",
                    shown ? "scale-100 opacity-100" : "scale-105 opacity-0",
                  )}
                />
                {!shown && (
                  <div className="absolute inset-0 animate-pulse bg-gradient-to-br from-white/5 to-transparent" />
                )}
                {tile.boxes.map((b) => (
                  <div
                    key={b.label + b.cx}
                    className={cn(
                      "absolute rounded-sm border-2 transition-all duration-500",
                      boxed ? "scale-100 opacity-100" : "scale-110 opacity-0",
                    )}
                    style={{
                      borderColor: b.color,
                      left: `${(b.cx - b.w / 2) * 100}%`,
                      top: `${(b.cy - b.h / 2) * 100}%`,
                      width: `${b.w * 100}%`,
                      height: `${b.h * 100}%`,
                    }}
                  >
                    <span
                      className="absolute -top-5 left-0 rounded-sm px-1 py-px text-[10px] font-medium whitespace-nowrap text-zinc-950"
                      style={{ backgroundColor: b.color }}
                    >
                      {b.label} ✓
                    </span>
                  </div>
                ))}
              </div>
            );
          })}
        </div>

        {/* status / training / done */}
        <div className="flex justify-center pt-1 sm:pt-3">
          <div className="flex h-10 min-w-0 items-center gap-3 rounded-full border bg-card px-5 shadow-xl">
            {done ? (
              <>
                <span className="flex size-4 shrink-0 items-center justify-center rounded-full bg-emerald-400">
                  <Check className="size-3 text-zinc-950" />
                </span>
                <p className="truncate text-xs font-medium text-emerald-400">{status}</p>
                <span className="hidden shrink-0 rounded-full border border-emerald-400/40 bg-emerald-400/10 px-2.5 py-0.5 text-[11px] text-emerald-400 sm:block">
                  0 human labels
                </span>
              </>
            ) : (
              <>
                <span
                  className={cn(
                    "size-1.5 shrink-0 rounded-full",
                    training ? "bg-primary" : "animate-pulse bg-muted-foreground",
                  )}
                />
                <p className="truncate text-xs text-muted-foreground">{status}</p>
                {training && (
                  <div className="h-1.5 w-24 shrink-0 overflow-hidden rounded-full bg-white/10 sm:w-32">
                    <div
                      className="h-full rounded-full bg-primary transition-all duration-300"
                      style={{ width: `${progress * 100}%` }}
                    />
                  </div>
                )}
              </>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
