"use client";

import {
  Bot,
  Car,
  Factory,
  Radar,
  ShoppingCart,
  Warehouse,
  Wheat,
  type LucideIcon,
} from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { Skeleton17 } from "@/components/datasets/bbox-image";
import { minAreaRect } from "@/lib/geometry";
import { cn } from "@/lib/utils";
import { INDUSTRY_OVERLAYS } from "./industry-overlays";

/* Every `image` is REAL aionVIS output: generated by the Synthesis Agent
   (FLUX.2) on the MI300X from that industry's use-case sentence, in a full
   swarm run (labeled by SAM 3, verified by the Critic). Sources live under
   public/industries/; a null image falls back to the placeholder tile.

   The boxes are the images' REAL stored labels (dataset records,
   runs 0015–0025, 2026-07-11), with two transforms applied:
   - display rule: every stored box with conf ≥ 0.35, no per-class cap —
     the tiles show the swarm's full output, not a sample; `chip` marks
     each class's highest-confidence box, which carries the label pill.
     Per-box source confidences are in the comments.
   - coordinates are re-normalized from the square source image to the
     tiles' 4:3 center crop: cy' = (cy − 0.125) / 0.75, h' = h / 0.75. */
type Box = {
  label: string;
  color: string;
  cx: number;
  cy: number;
  w: number;
  h: number;
  chip?: boolean;
};

const INDUSTRIES: {
  icon: LucideIcon;
  name: string;
  blurb: string;
  image: string | null;
  boxes: Box[];
}[] = [
  {
    icon: Factory,
    name: "AI in Manufacturing",
    blurb:
      "Defect, weld and PPE detectors trained from a sentence - quality control models without a single hand-drawn box.",
    image: "/industries/manufacturing.jpg",
    // ds_0017/img_0001.jpg - bottling-line run (run_0025)
    boxes: [
      { label: "bottle", color: "#d97706", cx: 0.1411, cy: 0.8361, w: 0.0695, h: 0.1568, chip: true }, // conf 0.909
      { label: "bottle", color: "#d97706", cx: 0.2421, cy: 0.6167, w: 0.051, h: 0.1521 }, // conf 0.904
      { label: "bottle", color: "#d97706", cx: 0.28, cy: 0.5489, w: 0.0498, h: 0.1197 }, // conf 0.898
      { label: "bottle", color: "#d97706", cx: 0.1983, cy: 0.7193, w: 0.0529, h: 0.1563 }, // conf 0.898
      { label: "bottle", color: "#d97706", cx: 0.3345, cy: 0.4443, w: 0.0482, h: 0.1219 }, // conf 0.879
      { label: "bottle", color: "#d97706", cx: 0.3841, cy: 0.3573, w: 0.042, h: 0.1355 }, // conf 0.878
      { label: "bottle", color: "#d97706", cx: 0.4926, cy: 0.5448, w: 0.0531, h: 0.1771 }, // conf 0.877
      { label: "bottle", color: "#d97706", cx: 0.4686, cy: 0.6536, w: 0.0559, h: 0.1803 }, // conf 0.877
      { label: "bottle", color: "#d97706", cx: 0.4475, cy: 0.7481, w: 0.0527, h: 0.164 }, // conf 0.864
      { label: "bottle", color: "#d97706", cx: 0.3379, cy: 0.5781, w: 0.0449, h: 0.0989 }, // conf 0.857
      { label: "bottle", color: "#d97706", cx: 0.3638, cy: 0.5429, w: 0.0396, h: 0.1068 }, // conf 0.856
      { label: "bottle", color: "#d97706", cx: 0.4152, cy: 0.8372, w: 0.0664, h: 0.1755 }, // conf 0.853
      { label: "bottle", color: "#d97706", cx: 0.4631, cy: 0.18, w: 0.0348, h: 0.1084 }, // conf 0.847
      { label: "bottle", color: "#d97706", cx: 0.1757, cy: 0.9964, w: 0.0751, h: 0.1615 }, // conf 0.843
      { label: "bottle", color: "#d97706", cx: 0.3887, cy: 0.4784, w: 0.0367, h: 0.0943 }, // conf 0.841
      { label: "bottle", color: "#d97706", cx: 0.4914, cy: 0.1127, w: 0.0375, h: 0.1185 }, // conf 0.84
      { label: "bottle", color: "#d97706", cx: 0.2871, cy: 0.7065, w: 0.05, h: 0.1265 }, // conf 0.832
      { label: "bottle", color: "#d97706", cx: 0.4385, cy: 0.22, w: 0.0277, h: 0.0916 }, // conf 0.824
      { label: "bottle", color: "#d97706", cx: 0.5422, cy: 0.0149, w: 0.0312, h: 0.1081 }, // conf 0.821
      { label: "bottle", color: "#d97706", cx: 0.3861, cy: 0.9511, w: 0.0746, h: 0.2125 }, // conf 0.82
      { label: "bottle", color: "#d97706", cx: 0.2246, cy: 0.8596, w: 0.0723, h: 0.2099 }, // conf 0.814
      { label: "bottle", color: "#d97706", cx: 0.0486, cy: 0.9683, w: 0.0973, h: 0.1885 }, // conf 0.814
      { label: "bottle", color: "#d97706", cx: 0.5229, cy: 0.4792, w: 0.0441, h: 0.1625 }, // conf 0.811
      { label: "bottle", color: "#d97706", cx: 0.5414, cy: 0.3972, w: 0.0391, h: 0.1339 }, // conf 0.809
      { label: "bottle", color: "#d97706", cx: 0.251, cy: 0.7735, w: 0.0605, h: 0.1531 }, // conf 0.808
      { label: "bottle", color: "#d97706", cx: 0.4184, cy: 0.2631, w: 0.0391, h: 0.1297 }, // conf 0.808
      { label: "bottle", color: "#d97706", cx: 0.4385, cy: 0.3347, w: 0.0316, h: 0.0912 }, // conf 0.799
      { label: "bottle", color: "#d97706", cx: 0.418, cy: 0.4047, w: 0.0359, h: 0.1073 }, // conf 0.797
      { label: "bottle", color: "#d97706", cx: 0.5738, cy: 0.3191, w: 0.0273, h: 0.1183 }, // conf 0.792
      { label: "bottle", color: "#d97706", cx: 0.4562, cy: 0.296, w: 0.0312, h: 0.0872 }, // conf 0.779
      { label: "bottle", color: "#d97706", cx: 0.5553, cy: 0.3527, w: 0.0285, h: 0.1125 }, // conf 0.768
      { label: "bottle", color: "#d97706", cx: 0.4004, cy: 0.7148, w: 0.0437, h: 0.0973 }, // conf 0.762
      { label: "bottle", color: "#d97706", cx: 0.5807, cy: 0.2611, w: 0.0301, h: 0.1268 }, // conf 0.754
      { label: "bottle", color: "#d97706", cx: 0.3184, cy: 0.5151, w: 0.0238, h: 0.0469 }, // conf 0.75
      { label: "bottle", color: "#d97706", cx: 0.3099, cy: 0.6484, w: 0.0791, h: 0.1031 }, // conf 0.742
      { label: "bottle", color: "#d97706", cx: 0.6123, cy: 0.1661, w: 0.0293, h: 0.1287 }, // conf 0.742
      { label: "bottle", color: "#d97706", cx: 0.4955, cy: 0.4087, w: 0.0324, h: 0.1013 }, // conf 0.736
      { label: "bottle", color: "#d97706", cx: 0.4191, cy: 0.6385, w: 0.0477, h: 0.1251 }, // conf 0.716
      { label: "bottle", color: "#d97706", cx: 0.6332, cy: 0.0947, w: 0.0312, h: 0.1305 }, // conf 0.696
      { label: "bottle", color: "#d97706", cx: 0.4869, cy: 0.232, w: 0.0355, h: 0.0937 }, // conf 0.689
      { label: "bottle", color: "#d97706", cx: 0.5191, cy: 0.0511, w: 0.0227, h: 0.0747 }, // conf 0.687
      { label: "bottle", color: "#d97706", cx: 0.5043, cy: 0.1771, w: 0.0312, h: 0.0667 }, // conf 0.685
      { label: "bottle", color: "#d97706", cx: 0.3386, cy: 0.8781, w: 0.0615, h: 0.1063 }, // conf 0.639
      { label: "bottle", color: "#d97706", cx: 0.4506, cy: 0.5651, w: 0.0293, h: 0.0937 }, // conf 0.632
      { label: "bottle", color: "#d97706", cx: 0.5961, cy: 0.2341, w: 0.0266, h: 0.1016 }, // conf 0.607
      { label: "bottle", color: "#d97706", cx: 0.3921, cy: 0.3112, w: 0.0299, h: 0.0776 }, // conf 0.603
      { label: "bottle", color: "#d97706", cx: 0.5461, cy: 0.2541, w: 0.0312, h: 0.086 }, // conf 0.594
      { label: "bottle", color: "#d97706", cx: 0.5711, cy: 0.1979, w: 0.0234, h: 0.0751 }, // conf 0.546
      { label: "bottle", color: "#d97706", cx: 0.5352, cy: 0.3001, w: 0.0297, h: 0.0721 }, // conf 0.541
      { label: "bottle", color: "#d97706", cx: 0.5297, cy: 0.1251, w: 0.0437, h: 0.0945 }, // conf 0.538
      { label: "bottle", color: "#d97706", cx: 0.3359, cy: 0.8667, w: 0.0625, h: 0.1251 }, // conf 0.511
      { label: "bottle", color: "#d97706", cx: 0.6113, cy: 0.0913, w: 0.0195, h: 0.0487 }, // conf 0.505
      { label: "bottle", color: "#d97706", cx: 0.4672, cy: 0.4861, w: 0.0273, h: 0.0797 }, // conf 0.422
      { label: "bottle", color: "#d97706", cx: 0.4609, cy: 0.2385, w: 0.025, h: 0.0479 }, // conf 0.407
      { label: "bottle", color: "#d97706", cx: 0.5312, cy: 0.2969, w: 0.0312, h: 0.0604 }, // conf 0.4
      { label: "bottle", color: "#d97706", cx: 0.3033, cy: 0.9521, w: 0.0371, h: 0.0708 }, // conf 0.393
      { label: "bottle", color: "#d97706", cx: 0.3609, cy: 0.8133, w: 0.0508, h: 0.0797 }, // conf 0.374
      { label: "bottle", color: "#d97706", cx: 0.5586, cy: 0.0396, w: 0.0328, h: 0.0959 }, // conf 0.351
      { label: "worker", color: "#65a30d", cx: 0.7434, cy: 0.7052, w: 0.2148, h: 0.5896, chip: true }, // conf 0.982
    ],
  },
  {
    icon: Car,
    name: "AI in Automotive",
    blurb:
      "Detect panels, parts and assembly states on the line, and retrain in minutes when the product changes.",
    image: "/industries/automotive.jpg",
    // ds_0014/img_0008.jpg - assembly-line run (run_0023)
    boxes: [
      { label: "car body", color: "#d97706", cx: 0.6885, cy: 0.5849, w: 0.623, h: 0.7136, chip: true }, // conf 0.922
      { label: "wheel", color: "#0284c7", cx: 0.4502, cy: 0.6197, w: 0.0715, h: 0.1511, chip: true }, // conf 0.54
      { label: "wheel", color: "#0284c7", cx: 0.8914, cy: 0.4305, w: 0.0578, h: 0.1099 }, // conf 0.408
      { label: "worker", color: "#65a30d", cx: 0.2294, cy: 0.6021, w: 0.2725, h: 0.85, chip: true }, // conf 0.986
      { label: "worker", color: "#65a30d", cx: 0.1214, cy: 0.4375, w: 0.0519, h: 0.1989 }, // conf 0.911
    ],
  },
  {
    icon: Wheat,
    name: "AI in Agriculture",
    blurb:
      "Crop, livestock and machinery detection for fields where nobody wants to hand-label ten thousand aerial photos.",
    image: "/industries/agriculture.jpg",
    // ds_0008/img_0005.jpg - farm run (run_0015)
    boxes: [
      { label: "hay bale", color: "#0284c7", cx: 0.0783, cy: 0.9448, w: 0.1566, h: 0.4375, chip: true }, // conf 0.912
      { label: "hay bale", color: "#0284c7", cx: 0.187, cy: 0.8721, w: 0.3338, h: 0.4473 }, // conf 0.859
      { label: "hay bale", color: "#0284c7", cx: 0.461, cy: 0.9765, w: 0.2264, h: 0.3303 }, // conf 0.852
      { label: "hay bale", color: "#0284c7", cx: 0.1467, cy: 0.4931, w: 0.2934, h: 0.3325 }, // conf 0.823
      { label: "hay bale", color: "#0284c7", cx: 0.3318, cy: 0.7284, w: 0.2707, h: 0.3088 }, // conf 0.77
      { label: "hay bale", color: "#0284c7", cx: 0.2119, cy: 0.4771, w: 0.1645, h: 0.2812 }, // conf 0.56
      { label: "hay bale", color: "#0284c7", cx: 0.3803, cy: 0.6935, w: 0.1707, h: 0.2464 }, // conf 0.452
      { label: "hay bale", color: "#0284c7", cx: 0.0987, cy: 0.4916, w: 0.1975, h: 0.3312 }, // conf 0.366
      { label: "cow", color: "#65a30d", cx: 0.5483, cy: 0.5524, w: 0.6236, h: 0.7161, chip: true }, // conf 0.981
    ],
  },
  {
    icon: Bot,
    name: "AI in Robotics",
    blurb:
      "Give a robot eyes for new objects overnight - synthetic scenes cover bins, grips and clutter before the robot ever sees them.",
    image: "/industries/robotics.jpg",
    // ds_0012/img_0002.jpg - cluttered-aisle run (run_0016)
    boxes: [
      { label: "box", color: "#d97706", cx: 0.4847, cy: 0.294, w: 0.7354, h: 0.3016, chip: true }, // conf 0.958
      { label: "box", color: "#d97706", cx: 0.4846, cy: 0.7167, w: 0.7104, h: 0.3125 }, // conf 0.955
      { label: "box", color: "#d97706", cx: 0.4886, cy: 0.5429, w: 0.7243, h: 0.2693 }, // conf 0.924
      { label: "box", color: "#d97706", cx: 0.9746, cy: 0.396, w: 0.0508, h: 0.0809 }, // conf 0.774
      { label: "box", color: "#d97706", cx: 0.9684, cy: 0.5003, w: 0.0633, h: 0.1369 }, // conf 0.75
      { label: "box", color: "#d97706", cx: 0.9707, cy: 0.4563, w: 0.0586, h: 0.0448 }, // conf 0.456
      { label: "box", color: "#d97706", cx: 0.9684, cy: 0.5213, w: 0.0633, h: 0.0948 }, // conf 0.434
      { label: "shelf", color: "#65a30d", cx: 0.8258, cy: 0.7177, w: 0.3453, h: 0.3355, chip: true }, // conf 0.8
      { label: "shelf", color: "#65a30d", cx: 0.8289, cy: 0.7167, w: 0.3391, h: 0.3333 }, // conf 0.501
      { label: "shelf", color: "#65a30d", cx: 0.8266, cy: 0.7156, w: 0.3469, h: 0.3385 }, // conf 0.489
    ],
  },
  {
    icon: Warehouse,
    name: "AI in Logistics",
    blurb:
      "Forklifts, pallets and safety vests from one sentence - the exact domain the live demo trains end to end.",
    image: "/industries/logistics.jpg",
    // ds_0009/img_0007.jpg - warehouse-safety run (run_0017)
    boxes: [
      { label: "forklift", color: "#d97706", cx: 0.6117, cy: 0.4825, w: 0.3398, h: 0.5964, chip: true }, // conf 0.964
      { label: "forklift", color: "#d97706", cx: 0.0576, cy: 0.3539, w: 0.0784, h: 0.1369 }, // conf 0.417
      { label: "pallet", color: "#0284c7", cx: 0.1947, cy: 0.5177, w: 0.1493, h: 0.0708, chip: true }, // conf 0.927
      { label: "pallet", color: "#0284c7", cx: 0.0808, cy: 0.8229, w: 0.1614, h: 0.2375 }, // conf 0.913
      { label: "pallet", color: "#0284c7", cx: 0.8086, cy: 0.52, w: 0.0875, h: 0.0735 }, // conf 0.894
      { label: "pallet", color: "#0284c7", cx: 0.9176, cy: 0.4399, w: 0.0867, h: 0.0765 }, // conf 0.884
      { label: "pallet", color: "#0284c7", cx: 0.8785, cy: 0.6341, w: 0.082, h: 0.112 }, // conf 0.881
      { label: "pallet", color: "#0284c7", cx: 0.9508, cy: 0.2405, w: 0.0984, h: 0.0372 }, // conf 0.833
      { label: "pallet", color: "#0284c7", cx: 0.9449, cy: 0.8817, w: 0.1102, h: 0.3031 }, // conf 0.826
      { label: "pallet", color: "#0284c7", cx: 0.3434, cy: 0.4219, w: 0.0703, h: 0.0197 }, // conf 0.747
      { label: "pallet", color: "#0284c7", cx: 0.3462, cy: 0.1992, w: 0.1006, h: 0.0255 }, // conf 0.544
      { label: "pallet", color: "#0284c7", cx: 0.1912, cy: 0.2127, w: 0.0816, h: 0.02 }, // conf 0.533
      { label: "pallet", color: "#0284c7", cx: 0.2581, cy: 0.2019, w: 0.0424, h: 0.0131 }, // conf 0.507
      { label: "pallet", color: "#0284c7", cx: 0.0745, cy: 0.2369, w: 0.0426, h: 0.0161 }, // conf 0.474
      { label: "pallet", color: "#0284c7", cx: 0.1013, cy: 0.4643, w: 0.0232, h: 0.0369 }, // conf 0.467
      { label: "pallet", color: "#0284c7", cx: 0.9719, cy: 0.9565, w: 0.0563, h: 0.1579 }, // conf 0.408
      { label: "pallet", color: "#0284c7", cx: 0.7549, cy: 0.4193, w: 0.0254, h: 0.0229 }, // conf 0.381
      { label: "worker", color: "#65a30d", cx: 0.4148, cy: 0.4463, w: 0.0734, h: 0.3117, chip: true }, // conf 0.94
      { label: "worker", color: "#65a30d", cx: 0.5465, cy: 0.3433, w: 0.0242, h: 0.0404 }, // conf 0.399
    ],
  },
  {
    icon: ShoppingCart,
    name: "AI in Retail",
    blurb:
      "Shelf gaps, planogram drift and queue counts - describe the shelf, get the detector.",
    image: "/industries/retail.jpg",
    // ds_0011/img_0005.jpg - supermarket-aisle run (run_0018)
    boxes: [
      { label: "cart", color: "#d97706", cx: 0.5211, cy: 0.836, w: 0.2188, h: 0.4969, chip: true }, // conf 0.977
      { label: "shopper", color: "#0284c7", cx: 0.4893, cy: 0.6049, w: 0.1762, h: 0.3161, chip: true }, // conf 0.817
      { label: "shelf", color: "#65a30d", cx: 0.8262, cy: 0.1297, w: 0.3477, h: 0.5719, chip: true }, // conf 0.836
      { label: "shelf", color: "#65a30d", cx: 0.1646, cy: 0.0399, w: 0.3293, h: 0.4131 }, // conf 0.826
      { label: "shelf", color: "#65a30d", cx: 0.8283, cy: 0.3964, w: 0.3434, h: 0.9635 }, // conf 0.782
      { label: "shelf", color: "#65a30d", cx: 0.7477, cy: 0.7344, w: 0.0859, h: 0.3771 }, // conf 0.779
      { label: "shelf", color: "#65a30d", cx: 0.1786, cy: 0.3193, w: 0.3572, h: 0.8176 }, // conf 0.777
      { label: "shelf", color: "#65a30d", cx: 0.2348, cy: 0.6555, w: 0.2918, h: 1.0224 }, // conf 0.753
      { label: "shelf", color: "#65a30d", cx: 0.3389, cy: 0.1463, w: 0.0645, h: 0.2284 }, // conf 0.724
      { label: "shelf", color: "#65a30d", cx: 0.8205, cy: 0.5505, w: 0.3293, h: 1.2196 }, // conf 0.703
      { label: "shelf", color: "#65a30d", cx: 0.143, cy: 0.8437, w: 0.1328, h: 0.4959 }, // conf 0.703
      { label: "shelf", color: "#65a30d", cx: 0.7012, cy: 0.3003, w: 0.1406, h: 0.5557 }, // conf 0.693
      { label: "shelf", color: "#65a30d", cx: 0.0562, cy: 0.2683, w: 0.0805, h: 0.124 }, // conf 0.677
      { label: "shelf", color: "#65a30d", cx: 0.1117, cy: 0.7489, w: 0.2234, h: 0.7063 }, // conf 0.603
      { label: "shelf", color: "#65a30d", cx: 0.8516, cy: 0.7136, w: 0.2594, h: 0.9021 }, // conf 0.597
      { label: "shelf", color: "#65a30d", cx: 0.6891, cy: 0.1427, w: 0.0906, h: 0.3271 }, // conf 0.58
      { label: "shelf", color: "#65a30d", cx: 0.2172, cy: 0.0253, w: 0.0531, h: 0.0789 }, // conf 0.562
      { label: "shelf", color: "#65a30d", cx: 0.14, cy: 0.1277, w: 0.1216, h: 0.1736 }, // conf 0.542
      { label: "shelf", color: "#65a30d", cx: 0.3652, cy: 0.2083, w: 0.0434, h: 0.1292 }, // conf 0.542
      { label: "shelf", color: "#65a30d", cx: 0.1655, cy: 0.5873, w: 0.3311, h: 1.0483 }, // conf 0.519
      { label: "shelf", color: "#65a30d", cx: 0.135, cy: 0.6844, w: 0.2699, h: 0.8645 }, // conf 0.496
      { label: "shelf", color: "#65a30d", cx: 0.1536, cy: 0.1151, w: 0.0876, h: 0.1281 }, // conf 0.474
      { label: "shelf", color: "#65a30d", cx: 0.3464, cy: 0.012, w: 0.0385, h: 0.0972 }, // conf 0.462
      { label: "shelf", color: "#65a30d", cx: 0.7172, cy: 0.3771, w: 0.1031, h: 0.4 }, // conf 0.455
      { label: "shelf", color: "#65a30d", cx: 0.8734, cy: 0.7763, w: 0.2203, h: 0.7807 }, // conf 0.451
      { label: "shelf", color: "#65a30d", cx: 0.6416, cy: 0.2027, w: 0.0441, h: 0.1979 }, // conf 0.42
      { label: "shelf", color: "#65a30d", cx: 0.8488, cy: 0.6741, w: 0.2695, h: 0.9809 }, // conf 0.405
      { label: "shelf", color: "#65a30d", cx: 0.8016, cy: 0.7729, w: 0.0531, h: 0.2249 }, // conf 0.404
      { label: "shelf", color: "#65a30d", cx: 0.6641, cy: 0.3085, w: 0.0844, h: 0.4057 }, // conf 0.388
      { label: "shelf", color: "#65a30d", cx: 0.1894, cy: 0.8284, w: 0.2025, h: 0.6765 }, // conf 0.377
      { label: "shelf", color: "#65a30d", cx: 0.0878, cy: 0.8347, w: 0.1756, h: 0.5599 }, // conf 0.369
      { label: "shelf", color: "#65a30d", cx: 0.8869, cy: 0.5404, w: 0.2262, h: 0.6609 }, // conf 0.367
      { label: "shelf", color: "#65a30d", cx: 0.3133, cy: 0.1419, w: 0.0645, h: 0.2027 }, // conf 0.363
      { label: "shelf", color: "#65a30d", cx: 0.718, cy: 0.3771, w: 0.1016, h: 0.4 }, // conf 0.36
    ],
  },
  {
    icon: Radar,
    name: "AI in Defense",
    blurb:
      "Aerial, maritime and perimeter detection where real imagery is scarce or classified - synthetic scenes fill the gap.",
    image: "/industries/defense.jpg",
    // ds_0016/img_0003.jpg - perimeter-drone run (run_0024)
    boxes: [
      { label: "drone", color: "#d97706", cx: 0.516, cy: 0.5143, w: 0.4297, h: 0.1995, chip: true }, // conf 0.965
    ],
  },
];

/** Landing-page mirror of the console's model-output views. */
export type OutputMode = "boxes" | "masks" | "obb" | "pose" | "labels";

export const OUTPUT_MODES: { id: OutputMode; label: string }[] = [
  { id: "masks", label: "Masks" },
  { id: "boxes", label: "Boxes" },
  { id: "obb", label: "Rotated boxes" },
  { id: "pose", label: "Pose" },
  { id: "labels", label: "Labels" },
];

function IndustryRow({
  mode,
  ariaHidden = false,
}: {
  mode: OutputMode;
  ariaHidden?: boolean;
}) {
  return (
    <div aria-hidden={ariaHidden || undefined} className="flex gap-4 pr-4">
      {INDUSTRIES.map(({ icon: Icon, name, blurb, image, boxes }) => {
        const overlays = INDUSTRY_OVERLAYS[name] ?? [];
        return (
        <article
          key={name}
          className="w-72 shrink-0 overflow-hidden rounded-xl border border-white/10 bg-card/40"
        >
          {/* overflow-hidden: stored boxes can extend past the 4:3 crop -
              clip them at the image edge instead of bleeding into the text */}
          <div className="relative flex aspect-[4/3] items-center justify-center overflow-hidden border-b border-white/5 bg-gradient-to-br from-muted/40 to-muted/10">
            {image ? (
              <>
                {/* eslint-disable-next-line @next/next/no-img-element -- fixed-size marquee tile, pre-sized asset */}
                <img
                  src={image}
                  alt={`Synthetic training image generated and labeled by aionVIS for ${name.replace("AI in ", "").toLowerCase()}`}
                  draggable={false}
                  className="absolute inset-0 h-full w-full object-cover"
                />
                {(mode === "masks" || mode === "obb" || mode === "pose") && (
                  <svg
                    aria-hidden
                    className="absolute inset-0 z-10 size-full"
                    viewBox="0 0 1 1"
                    preserveAspectRatio="none"
                  >
                    {boxes.map((b, i) => {
                      const ov = overlays[i];
                      if (mode === "pose") {
                        return ov?.keypoints ? (
                          <Skeleton17
                            key={i}
                            flat={ov.keypoints}
                            color={b.color}
                          />
                        ) : null;
                      }
                      if (!ov?.polygon) return null;
                      const flat =
                        mode === "obb"
                          ? minAreaRect(ov.polygon, 4 / 3)
                          : ov.polygon;
                      if (!flat) return null;
                      const pts: string[] = [];
                      for (let p = 0; p + 1 < flat.length; p += 2)
                        pts.push(`${flat[p]},${flat[p + 1]}`);
                      return (
                        <polygon
                          key={i}
                          points={pts.join(" ")}
                          fill={b.color}
                          fillOpacity={0.15}
                          stroke={b.color}
                          strokeWidth={1.5}
                          vectorEffect="non-scaling-stroke"
                          strokeLinejoin="round"
                        />
                      );
                    })}
                  </svg>
                )}
                {boxes.map((b, i) => {
                  // Pose is a person model: only skeleton-carrying labels
                  // exist in that output; the rest of the modes anchor all.
                  if (mode === "pose" && !overlays[i]?.keypoints) return null;
                  const bordered =
                    mode === "boxes" || mode === "pose";
                  return (
                  <div
                    key={b.label + b.cx}
                    className={cn(
                      "absolute rounded-[3px]",
                      bordered && "border-[1.5px]",
                      // Chipped boxes stack above bare outlines so the
                      // label pills are never covered.
                      b.chip ? "z-20" : "z-10",
                    )}
                    style={{
                      borderColor: b.color,
                      left: `${(b.cx - b.w / 2) * 100}%`,
                      top: `${(b.cy - b.h / 2) * 100}%`,
                      width: `${b.w * 100}%`,
                      height: `${b.h * 100}%`,
                    }}
                  >
                    {(b.chip || (mode === "pose" && overlays[i]?.keypoints)) && (
                      <span
                        className={cn(
                          "absolute -top-4 rounded-sm px-1 py-px text-[9px] leading-4 font-medium whitespace-nowrap text-zinc-950",
                          // Anchor right near the tile's right edge so the
                          // pill isn't clipped by overflow-hidden.
                          b.cx > 0.8 ? "right-0" : "left-0",
                        )}
                        style={{ backgroundColor: b.color }}
                      >
                        {b.label} ✓
                      </span>
                    )}
                  </div>
                  );
                })}
                <span className="absolute right-2 bottom-2 z-30 rounded bg-black/60 px-1.5 py-0.5 font-mono text-[10px] text-white/85 backdrop-blur-sm">
                  real aionVIS output · MI300X
                </span>
              </>
            ) : (
              <>
                <Icon aria-hidden className="size-8 text-muted-foreground/40" />
                <span className="absolute right-2.5 bottom-2 font-mono text-[10px] text-muted-foreground/50">
                  awaiting synthesis · MI300X
                </span>
              </>
            )}
          </div>
          <div className="p-4">
            <h3 className="text-sm font-semibold">{name}</h3>
            <p className="mt-1.5 text-xs leading-relaxed text-muted-foreground">
              {blurb}
            </p>
          </div>
        </article>
        );
      })}
    </div>
  );
}

/** One marquee loop takes this long when idle - matches the old CSS pace. */
const LOOP_SECONDS = 45;

/**
 * Infinite marquee, draggable. The track holds two identical rows, and a
 * rAF loop advances a pixel offset wrapped modulo one row's width - the
 * same seamless -50% trick as the old CSS animation, but interactive:
 * hovering pauses, dragging scrubs (pointer events, so touch works too).
 */
export function IndustryMarquee() {
  const trackRef = useRef<HTMLDivElement>(null);
  const [dragging, setDragging] = useState(false);
  // Same images, every model-output type — the same real labels the
  // console shows, cycled through the five representations we train.
  // Masks lead: they're the richest view of what SAM 3 actually labels.
  const [mode, setMode] = useState<OutputMode>("masks");
  const state = useRef({
    offset: 0,
    half: 0,
    paused: false,
    dragging: false,
    dragStartX: 0,
    dragStartOffset: 0,
  });

  useEffect(() => {
    const track = trackRef.current;
    if (!track) return;
    const s = state.current;

    const measure = () => {
      s.half = track.scrollWidth / 2;
    };
    measure();
    const ro = new ResizeObserver(measure);
    ro.observe(track);

    const reduceMotion = window.matchMedia(
      "(prefers-reduced-motion: reduce)",
    ).matches;

    let raf = 0;
    let last = performance.now();
    const tick = (now: number) => {
      const dt = (now - last) / 1000;
      last = now;
      if (!reduceMotion && !s.paused && !s.dragging && s.half > 0) {
        s.offset += (s.half / LOOP_SECONDS) * dt;
      }
      if (s.half > 0) {
        s.offset = ((s.offset % s.half) + s.half) % s.half;
        track.style.transform = `translate3d(${-s.offset}px, 0, 0)`;
      }
      raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    return () => {
      cancelAnimationFrame(raf);
      ro.disconnect();
    };
  }, []);

  const s = state.current;
  return (
    <div className="space-y-5">
      <div
        className="flex flex-wrap items-center justify-center gap-1.5"
        role="group"
        aria-label="Model output type"
      >
        {OUTPUT_MODES.map((m) => (
          <button
            key={m.id}
            type="button"
            onClick={() => setMode(m.id)}
            className={cn(
              "rounded-full border px-3 py-1 text-xs font-medium transition-all duration-200",
              mode === m.id
                ? "border-primary bg-primary/10 text-foreground shadow-sm shadow-primary/20"
                : "border-white/10 text-muted-foreground hover:border-muted-foreground/40 hover:text-foreground",
            )}
          >
            {m.label}
          </button>
        ))}
      </div>
    <div
      className={cn(
        "group relative touch-pan-y overflow-hidden",
        dragging ? "cursor-grabbing" : "cursor-grab",
      )}
      onMouseEnter={() => (s.paused = true)}
      onMouseLeave={() => (s.paused = false)}
      onPointerDown={(e) => {
        s.dragging = true;
        s.dragStartX = e.clientX;
        s.dragStartOffset = s.offset;
        setDragging(true);
        e.currentTarget.setPointerCapture(e.pointerId);
      }}
      onPointerMove={(e) => {
        if (!s.dragging) return;
        s.offset = s.dragStartOffset - (e.clientX - s.dragStartX);
      }}
      onPointerUp={() => {
        s.dragging = false;
        setDragging(false);
      }}
      onPointerCancel={() => {
        s.dragging = false;
        setDragging(false);
      }}
    >
      <div
        aria-hidden
        className="pointer-events-none absolute inset-y-0 left-0 z-10 w-16 bg-gradient-to-r from-background to-transparent sm:w-28"
      />
      <div
        aria-hidden
        className="pointer-events-none absolute inset-y-0 right-0 z-10 w-16 bg-gradient-to-l from-background to-transparent sm:w-28"
      />
      <div ref={trackRef} className="flex w-max select-none">
        <IndustryRow mode={mode} />
        <IndustryRow mode={mode} ariaHidden />
      </div>
    </div>
    </div>
  );
}
