"use client";

import {
  Bot,
  Car,
  Factory,
  Radar,
  ShoppingCart,
  Warehouse,
  Wheat,
  type LucideIcon,
} from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { cn } from "@/lib/utils";

/* Every `image` is REAL aionVIS output: generated by the Synthesis Agent
   (FLUX.2) on the MI300X from that industry's use-case sentence, in a full
   swarm run (labeled by SAM 3, verified by the Critic). Sources live under
   public/industries/; a null image falls back to the placeholder tile. */
const INDUSTRIES: {
  icon: LucideIcon;
  name: string;
  blurb: string;
  image: string | null;
}[] = [
  {
    icon: Factory,
    name: "AI in Manufacturing",
    blurb:
      "Defect, weld and PPE detectors trained from a sentence — quality control models without a single hand-drawn box.",
    image: "/industries/manufacturing.jpg",
  },
  {
    icon: Car,
    name: "AI in Automotive",
    blurb:
      "Detect panels, parts and assembly states on the line, and retrain in minutes when the product changes.",
    image: "/industries/automotive.jpg",
  },
  {
    icon: Wheat,
    name: "AI in Agriculture",
    blurb:
      "Crop, livestock and machinery detection for fields where nobody wants to hand-label ten thousand aerial photos.",
    image: "/industries/agriculture.jpg",
  },
  {
    icon: Bot,
    name: "AI in Robotics",
    blurb:
      "Give a robot eyes for new objects overnight — synthetic scenes cover bins, grips and clutter before the robot ever sees them.",
    image: "/industries/robotics.jpg",
  },
  {
    icon: Warehouse,
    name: "AI in Logistics",
    blurb:
      "Forklifts, pallets and safety vests from one sentence — the exact domain the live demo trains end to end.",
    image: "/industries/logistics.jpg",
  },
  {
    icon: ShoppingCart,
    name: "AI in Retail",
    blurb:
      "Shelf gaps, planogram drift and queue counts — describe the shelf, get the detector.",
    image: "/industries/retail.jpg",
  },
  {
    icon: Radar,
    name: "AI in Defense",
    blurb:
      "Aerial, maritime and perimeter detection where real imagery is scarce or classified — synthetic scenes fill the gap.",
    image: "/industries/defense.jpg",
  },
];

function IndustryRow({ ariaHidden = false }: { ariaHidden?: boolean }) {
  return (
    <div aria-hidden={ariaHidden || undefined} className="flex gap-4 pr-4">
      {INDUSTRIES.map(({ icon: Icon, name, blurb, image }) => (
        <article
          key={name}
          className="w-72 shrink-0 overflow-hidden rounded-xl border border-white/10 bg-card/40"
        >
          <div className="relative flex aspect-[4/3] items-center justify-center border-b border-white/5 bg-gradient-to-br from-muted/40 to-muted/10">
            {image ? (
              <>
                {/* eslint-disable-next-line @next/next/no-img-element -- fixed-size marquee tile, pre-sized asset */}
                <img
                  src={image}
                  alt={`Synthetic training image generated by aionVIS for ${name.replace("AI in ", "").toLowerCase()}`}
                  draggable={false}
                  className="absolute inset-0 h-full w-full object-cover"
                />
                <span className="absolute right-2 bottom-2 rounded bg-black/60 px-1.5 py-0.5 font-mono text-[10px] text-white/85 backdrop-blur-sm">
                  real aionVIS output · MI300X
                </span>
              </>
            ) : (
              <>
                <Icon aria-hidden className="size-8 text-muted-foreground/40" />
                <span className="absolute right-2.5 bottom-2 font-mono text-[10px] text-muted-foreground/50">
                  awaiting synthesis · MI300X
                </span>
              </>
            )}
          </div>
          <div className="p-4">
            <h3 className="text-sm font-semibold">{name}</h3>
            <p className="mt-1.5 text-xs leading-relaxed text-muted-foreground">
              {blurb}
            </p>
          </div>
        </article>
      ))}
    </div>
  );
}

/** One marquee loop takes this long when idle — matches the old CSS pace. */
const LOOP_SECONDS = 45;

/**
 * Infinite marquee, draggable. The track holds two identical rows, and a
 * rAF loop advances a pixel offset wrapped modulo one row's width — the
 * same seamless -50% trick as the old CSS animation, but interactive:
 * hovering pauses, dragging scrubs (pointer events, so touch works too).
 */
export function IndustryMarquee() {
  const trackRef = useRef<HTMLDivElement>(null);
  const [dragging, setDragging] = useState(false);
  const state = useRef({
    offset: 0,
    half: 0,
    paused: false,
    dragging: false,
    dragStartX: 0,
    dragStartOffset: 0,
  });

  useEffect(() => {
    const track = trackRef.current;
    if (!track) return;
    const s = state.current;

    const measure = () => {
      s.half = track.scrollWidth / 2;
    };
    measure();
    const ro = new ResizeObserver(measure);
    ro.observe(track);

    const reduceMotion = window.matchMedia(
      "(prefers-reduced-motion: reduce)",
    ).matches;

    let raf = 0;
    let last = performance.now();
    const tick = (now: number) => {
      const dt = (now - last) / 1000;
      last = now;
      if (!reduceMotion && !s.paused && !s.dragging && s.half > 0) {
        s.offset += (s.half / LOOP_SECONDS) * dt;
      }
      if (s.half > 0) {
        s.offset = ((s.offset % s.half) + s.half) % s.half;
        track.style.transform = `translate3d(${-s.offset}px, 0, 0)`;
      }
      raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    return () => {
      cancelAnimationFrame(raf);
      ro.disconnect();
    };
  }, []);

  const s = state.current;
  return (
    <div
      className={cn(
        "group relative touch-pan-y overflow-hidden",
        dragging ? "cursor-grabbing" : "cursor-grab",
      )}
      onMouseEnter={() => (s.paused = true)}
      onMouseLeave={() => (s.paused = false)}
      onPointerDown={(e) => {
        s.dragging = true;
        s.dragStartX = e.clientX;
        s.dragStartOffset = s.offset;
        setDragging(true);
        e.currentTarget.setPointerCapture(e.pointerId);
      }}
      onPointerMove={(e) => {
        if (!s.dragging) return;
        s.offset = s.dragStartOffset - (e.clientX - s.dragStartX);
      }}
      onPointerUp={() => {
        s.dragging = false;
        setDragging(false);
      }}
      onPointerCancel={() => {
        s.dragging = false;
        setDragging(false);
      }}
    >
      <div
        aria-hidden
        className="pointer-events-none absolute inset-y-0 left-0 z-10 w-16 bg-gradient-to-r from-background to-transparent sm:w-28"
      />
      <div
        aria-hidden
        className="pointer-events-none absolute inset-y-0 right-0 z-10 w-16 bg-gradient-to-l from-background to-transparent sm:w-28"
      />
      <div ref={trackRef} className="flex w-max select-none">
        <IndustryRow />
        <IndustryRow ariaHidden />
      </div>
    </div>
  );
}
