"use client";

import {
  Bot,
  Car,
  Factory,
  Radar,
  ShoppingCart,
  Warehouse,
  Wheat,
  type LucideIcon,
} from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { Skeleton17 } from "@/components/datasets/bbox-image";
import { minAreaRect } from "@/lib/geometry";
import { cn } from "@/lib/utils";
import { INDUSTRY_OVERLAYS } from "./industry-overlays";

/* Every `image` is REAL aionVIS output: generated by the Synthesis Agent
   (FLUX.2) on the MI300X from that industry's use-case sentence, in a full
   swarm run (labeled by SAM 3, verified by the Critic). Sources live under
   public/industries/; a null image falls back to the placeholder tile.

   The boxes are the images' REAL stored labels (dataset records,
   runs 0015–0025, 2026-07-11), with two transforms applied:
   - display rule for these small tiles: conf ≥ 0.50, top 5 boxes per
     class (the hero, at 3× the size, draws every stored box ≥ 0.50);
     `chip` marks each class's highest-confidence box, which carries the
     label pill. Per-box source confidences are in the comments.
   - coordinates are re-normalized from the square source image to the
     tiles' 4:3 center crop: cy' = (cy − 0.125) / 0.75, h' = h / 0.75. */
type Box = {
  label: string;
  color: string;
  cx: number;
  cy: number;
  w: number;
  h: number;
  chip?: boolean;
};

const INDUSTRIES: {
  icon: LucideIcon;
  name: string;
  blurb: string;
  image: string | null;
  boxes: Box[];
}[] = [
  {
    icon: Factory,
    name: "AI in Manufacturing",
    blurb:
      "Defect, weld and PPE detectors trained from a sentence - quality control models without a single hand-drawn box.",
    image: "/industries/manufacturing.jpg",
    // ds_0017/img_0010.jpg - bottling-line run (run_0025)
    boxes: [
      { label: "bottle", color: "#d97706", cx: 0.3945, cy: 0.7839, w: 0.0664, h: 0.1636, chip: true }, // conf 0.934
      { label: "bottle", color: "#d97706", cx: 0.3599, cy: 0.8661, w: 0.0732, h: 0.1593 }, // conf 0.934
      { label: "bottle", color: "#d97706", cx: 0.4385, cy: 0.974, w: 0.0637, h: 0.1396 }, // conf 0.934
      { label: "bottle", color: "#d97706", cx: 0.4678, cy: 0.8281, w: 0.0535, h: 0.1708 }, // conf 0.93
      { label: "bottle", color: "#d97706", cx: 0.4684, cy: 0.6131, w: 0.0508, h: 0.1511 }, // conf 0.928
      { label: "worker", color: "#65a30d", cx: 0.6377, cy: 0.4869, w: 0.3262, h: 0.5697, chip: true }, // conf 0.966
    ],
  },
  {
    icon: Car,
    name: "AI in Automotive",
    blurb:
      "Detect panels, parts and assembly states on the line, and retrain in minutes when the product changes.",
    image: "/industries/automotive.jpg",
    // ds_0014/img_0008.jpg - assembly-line run (run_0023)
    boxes: [
      { label: "car body", color: "#d97706", cx: 0.6885, cy: 0.5849, w: 0.623, h: 0.7136, chip: true }, // conf 0.922
      { label: "wheel", color: "#0284c7", cx: 0.4502, cy: 0.6197, w: 0.0715, h: 0.1511, chip: true }, // conf 0.54
      { label: "worker", color: "#65a30d", cx: 0.2294, cy: 0.6021, w: 0.2725, h: 0.85, chip: true }, // conf 0.986
      { label: "worker", color: "#65a30d", cx: 0.1214, cy: 0.4375, w: 0.0519, h: 0.1989 }, // conf 0.911
    ],
  },
  {
    icon: Wheat,
    name: "AI in Agriculture",
    blurb:
      "Crop, livestock and machinery detection for fields where nobody wants to hand-label ten thousand aerial photos.",
    image: "/industries/agriculture.jpg",
    // ds_0008/img_0005.jpg - farm run (run_0015)
    boxes: [
      { label: "hay bale", color: "#0284c7", cx: 0.0783, cy: 0.9448, w: 0.1566, h: 0.4375, chip: true }, // conf 0.912
      { label: "hay bale", color: "#0284c7", cx: 0.187, cy: 0.8721, w: 0.3338, h: 0.4473 }, // conf 0.859
      { label: "hay bale", color: "#0284c7", cx: 0.461, cy: 0.9765, w: 0.2264, h: 0.3303 }, // conf 0.852
      { label: "hay bale", color: "#0284c7", cx: 0.1467, cy: 0.4931, w: 0.2934, h: 0.3325 }, // conf 0.823
      { label: "hay bale", color: "#0284c7", cx: 0.3318, cy: 0.7284, w: 0.2707, h: 0.3088 }, // conf 0.77
      { label: "cow", color: "#65a30d", cx: 0.5483, cy: 0.5524, w: 0.6236, h: 0.7161, chip: true }, // conf 0.981
    ],
  },
  {
    icon: Bot,
    name: "AI in Robotics",
    blurb:
      "Give a robot eyes for new objects overnight - synthetic scenes cover bins, grips and clutter before the robot ever sees them.",
    image: "/industries/robotics.jpg",
    // ds_0012/img_0004.jpg - cluttered-aisle run (run_0016)
    boxes: [
      { label: "box", color: "#d97706", cx: 0.0405, cy: 0.9565, w: 0.0811, h: 0.2057, chip: true }, // conf 0.901
      { label: "box", color: "#d97706", cx: 0.7852, cy: 0.6011, w: 0.0719, h: 0.0885 }, // conf 0.888
      { label: "box", color: "#d97706", cx: 0.0391, cy: 0.4751, w: 0.0781, h: 0.1167 }, // conf 0.888
      { label: "box", color: "#d97706", cx: 0.1841, cy: 0.9437, w: 0.0579, h: 0.1625 }, // conf 0.884
      { label: "box", color: "#d97706", cx: 0.8176, cy: 0.6177, w: 0.0227, h: 0.0729 }, // conf 0.872
      { label: "bin", color: "#0284c7", cx: 0.868, cy: 0.134, w: 0.0703, h: 0.1789, chip: true }, // conf 0.863
      { label: "bin", color: "#0284c7", cx: 0.1872, cy: 0.8573, w: 0.0636, h: 0.0833 }, // conf 0.848
      { label: "bin", color: "#0284c7", cx: 0.7809, cy: 0.2452, w: 0.043, h: 0.1232 }, // conf 0.835
      { label: "bin", color: "#0284c7", cx: 0.2096, cy: 0.8159, w: 0.1019, h: 0.0609 }, // conf 0.82
      { label: "bin", color: "#0284c7", cx: 0.7855, cy: 0.8719, w: 0.0445, h: 0.1292 }, // conf 0.816
      { label: "shelf", color: "#65a30d", cx: 0.8199, cy: 0.5188, w: 0.1727, h: 0.05, chip: true }, // conf 0.769
      { label: "shelf", color: "#65a30d", cx: 0.0464, cy: 0.7063, w: 0.0929, h: 0.0688 }, // conf 0.761
      { label: "shelf", color: "#65a30d", cx: 0.9586, cy: 0.4981, w: 0.0828, h: 0.0568 }, // conf 0.754
      { label: "shelf", color: "#65a30d", cx: 0.8193, cy: 0.6817, w: 0.1738, h: 0.0948 }, // conf 0.739
      { label: "shelf", color: "#65a30d", cx: 0.8164, cy: 0.0187, w: 0.1703, h: 0.356 }, // conf 0.732
    ],
  },
  {
    icon: Warehouse,
    name: "AI in Logistics",
    blurb:
      "Forklifts, pallets and safety vests from one sentence - the exact domain the live demo trains end to end.",
    image: "/industries/logistics.jpg",
    // ds_0009/img_0007.jpg - warehouse-safety run (run_0017)
    boxes: [
      { label: "forklift", color: "#d97706", cx: 0.6117, cy: 0.4825, w: 0.3398, h: 0.5964, chip: true }, // conf 0.964
      { label: "pallet", color: "#0284c7", cx: 0.1947, cy: 0.5177, w: 0.1493, h: 0.0708, chip: true }, // conf 0.927
      { label: "pallet", color: "#0284c7", cx: 0.0808, cy: 0.8229, w: 0.1614, h: 0.2375 }, // conf 0.913
      { label: "pallet", color: "#0284c7", cx: 0.8086, cy: 0.52, w: 0.0875, h: 0.0735 }, // conf 0.894
      { label: "pallet", color: "#0284c7", cx: 0.9176, cy: 0.4399, w: 0.0867, h: 0.0765 }, // conf 0.884
      { label: "pallet", color: "#0284c7", cx: 0.8785, cy: 0.6341, w: 0.082, h: 0.112 }, // conf 0.881
      { label: "worker", color: "#65a30d", cx: 0.4148, cy: 0.4463, w: 0.0734, h: 0.3117, chip: true }, // conf 0.94
    ],
  },
  {
    icon: ShoppingCart,
    name: "AI in Retail",
    blurb:
      "Shelf gaps, planogram drift and queue counts - describe the shelf, get the detector.",
    image: "/industries/retail.jpg",
    // ds_0011/img_0002.jpg - supermarket-aisle run (run_0018)
    boxes: [
      { label: "cart", color: "#d97706", cx: 0.6793, cy: 0.8052, w: 0.2352, h: 0.4396, chip: true }, // conf 0.972
      { label: "cart", color: "#d97706", cx: 0.3345, cy: 0.8047, w: 0.1959, h: 0.426 }, // conf 0.967
      { label: "cart", color: "#d97706", cx: 0.4002, cy: 0.4669, w: 0.1059, h: 0.2797 }, // conf 0.83
      { label: "shopper", color: "#0284c7", cx: 0.6082, cy: 0.3292, w: 0.0898, h: 0.3177, chip: true }, // conf 0.963
      { label: "shopper", color: "#0284c7", cx: 0.4717, cy: 0.3547, w: 0.0926, h: 0.3541 }, // conf 0.949
      { label: "shopper", color: "#0284c7", cx: 0.5352, cy: 0.2093, w: 0.0766, h: 0.2887 }, // conf 0.94
      { label: "shopper", color: "#0284c7", cx: 0.7299, cy: 0.5073, w: 0.148, h: 0.2604 }, // conf 0.902
      { label: "shopper", color: "#0284c7", cx: 0.5104, cy: 0.0396, w: 0.0293, h: 0.1405 }, // conf 0.869
      { label: "shelf", color: "#65a30d", cx: 0.1503, cy: 0.3196, w: 0.135, h: 0.1648, chip: true }, // conf 0.769
      { label: "shelf", color: "#65a30d", cx: 0.0762, cy: 0.8412, w: 0.1523, h: 0.4303 }, // conf 0.746
      { label: "shelf", color: "#65a30d", cx: 0.1765, cy: 0.4607, w: 0.0955, h: 0.1464 }, // conf 0.737
      { label: "shelf", color: "#65a30d", cx: 0.1857, cy: 0.0007, w: 0.1017, h: 0.0364 }, // conf 0.733
      { label: "shelf", color: "#65a30d", cx: 0.9027, cy: 0.0772, w: 0.1945, h: 0.1081 }, // conf 0.726
    ],
  },
  {
    icon: Radar,
    name: "AI in Defense",
    blurb:
      "Aerial, maritime and perimeter detection where real imagery is scarce or classified - synthetic scenes fill the gap.",
    image: "/industries/defense.jpg",
    // ds_0016/img_0003.jpg - perimeter-drone run (run_0024)
    boxes: [
      { label: "drone", color: "#d97706", cx: 0.516, cy: 0.5143, w: 0.4297, h: 0.1995, chip: true }, // conf 0.965
    ],
  },
];

/** Landing-page mirror of the console's model-output views. */
export type OutputMode = "boxes" | "masks" | "obb" | "pose" | "labels";

export const OUTPUT_MODES: { id: OutputMode; label: string }[] = [
  { id: "masks", label: "Masks" },
  { id: "boxes", label: "Boxes" },
  { id: "obb", label: "Rotated boxes" },
  { id: "pose", label: "Pose" },
  { id: "labels", label: "Labels" },
];

function IndustryRow({
  mode,
  ariaHidden = false,
}: {
  mode: OutputMode;
  ariaHidden?: boolean;
}) {
  return (
    <div aria-hidden={ariaHidden || undefined} className="flex gap-4 pr-4">
      {INDUSTRIES.map(({ icon: Icon, name, blurb, image, boxes }) => {
        const overlays = INDUSTRY_OVERLAYS[name] ?? [];
        return (
        <article
          key={name}
          className="w-72 shrink-0 overflow-hidden rounded-xl border border-white/10 bg-card/40"
        >
          {/* overflow-hidden: stored boxes can extend past the 4:3 crop -
              clip them at the image edge instead of bleeding into the text */}
          <div className="relative flex aspect-[4/3] items-center justify-center overflow-hidden border-b border-white/5 bg-gradient-to-br from-muted/40 to-muted/10">
            {image ? (
              <>
                {/* eslint-disable-next-line @next/next/no-img-element -- fixed-size marquee tile, pre-sized asset */}
                <img
                  src={image}
                  alt={`Synthetic training image generated and labeled by aionVIS for ${name.replace("AI in ", "").toLowerCase()}`}
                  draggable={false}
                  className="absolute inset-0 h-full w-full object-cover"
                />
                {(mode === "masks" || mode === "obb" || mode === "pose") && (
                  <svg
                    aria-hidden
                    className="absolute inset-0 z-10 size-full"
                    viewBox="0 0 1 1"
                    preserveAspectRatio="none"
                  >
                    {boxes.map((b, i) => {
                      const ov = overlays[i];
                      if (mode === "pose") {
                        return ov?.keypoints ? (
                          <Skeleton17
                            key={i}
                            flat={ov.keypoints}
                            color={b.color}
                          />
                        ) : null;
                      }
                      if (!ov?.polygon) return null;
                      const flat =
                        mode === "obb"
                          ? minAreaRect(ov.polygon, 4 / 3)
                          : ov.polygon;
                      if (!flat) return null;
                      const pts: string[] = [];
                      for (let p = 0; p + 1 < flat.length; p += 2)
                        pts.push(`${flat[p]},${flat[p + 1]}`);
                      return (
                        <polygon
                          key={i}
                          points={pts.join(" ")}
                          fill={b.color}
                          fillOpacity={0.15}
                          stroke={b.color}
                          strokeWidth={1.5}
                          vectorEffect="non-scaling-stroke"
                          strokeLinejoin="round"
                        />
                      );
                    })}
                  </svg>
                )}
                {boxes.map((b, i) => {
                  // Pose is a person model: only skeleton-carrying labels
                  // exist in that output; the rest of the modes anchor all.
                  if (mode === "pose" && !overlays[i]?.keypoints) return null;
                  const bordered =
                    mode === "boxes" || mode === "pose";
                  return (
                  <div
                    key={b.label + b.cx}
                    className={cn(
                      "absolute rounded-[3px]",
                      bordered && "border-[1.5px]",
                      // Chipped boxes stack above bare outlines so the
                      // label pills are never covered.
                      b.chip ? "z-20" : "z-10",
                    )}
                    style={{
                      borderColor: b.color,
                      left: `${(b.cx - b.w / 2) * 100}%`,
                      top: `${(b.cy - b.h / 2) * 100}%`,
                      width: `${b.w * 100}%`,
                      height: `${b.h * 100}%`,
                    }}
                  >
                    {(b.chip || (mode === "pose" && overlays[i]?.keypoints)) && (
                      <span
                        className={cn(
                          "absolute -top-4 rounded-sm px-1 py-px text-[9px] leading-4 font-medium whitespace-nowrap text-zinc-950",
                          // Anchor right near the tile's right edge so the
                          // pill isn't clipped by overflow-hidden.
                          b.cx > 0.8 ? "right-0" : "left-0",
                        )}
                        style={{ backgroundColor: b.color }}
                      >
                        {b.label} ✓
                      </span>
                    )}
                  </div>
                  );
                })}
                <span className="absolute right-2 bottom-2 z-30 rounded bg-black/60 px-1.5 py-0.5 font-mono text-[10px] text-white/85 backdrop-blur-sm">
                  real aionVIS output · MI300X
                </span>
              </>
            ) : (
              <>
                <Icon aria-hidden className="size-8 text-muted-foreground/40" />
                <span className="absolute right-2.5 bottom-2 font-mono text-[10px] text-muted-foreground/50">
                  awaiting synthesis · MI300X
                </span>
              </>
            )}
          </div>
          <div className="p-4">
            <h3 className="text-sm font-semibold">{name}</h3>
            <p className="mt-1.5 text-xs leading-relaxed text-muted-foreground">
              {blurb}
            </p>
          </div>
        </article>
        );
      })}
    </div>
  );
}

/** One marquee loop takes this long when idle - matches the old CSS pace. */
const LOOP_SECONDS = 45;

/**
 * Infinite marquee, draggable. The track holds two identical rows, and a
 * rAF loop advances a pixel offset wrapped modulo one row's width - the
 * same seamless -50% trick as the old CSS animation, but interactive:
 * hovering pauses, dragging scrubs (pointer events, so touch works too).
 */
export function IndustryMarquee() {
  const trackRef = useRef<HTMLDivElement>(null);
  const [dragging, setDragging] = useState(false);
  // Same images, every model-output type — the same real labels the
  // console shows, cycled through the five representations we train.
  // Masks lead: they're the richest view of what SAM 3 actually labels.
  const [mode, setMode] = useState<OutputMode>("masks");
  const state = useRef({
    offset: 0,
    half: 0,
    paused: false,
    dragging: false,
    dragStartX: 0,
    dragStartOffset: 0,
  });

  useEffect(() => {
    const track = trackRef.current;
    if (!track) return;
    const s = state.current;

    const measure = () => {
      s.half = track.scrollWidth / 2;
    };
    measure();
    const ro = new ResizeObserver(measure);
    ro.observe(track);

    const reduceMotion = window.matchMedia(
      "(prefers-reduced-motion: reduce)",
    ).matches;

    let raf = 0;
    let last = performance.now();
    const tick = (now: number) => {
      const dt = (now - last) / 1000;
      last = now;
      if (!reduceMotion && !s.paused && !s.dragging && s.half > 0) {
        s.offset += (s.half / LOOP_SECONDS) * dt;
      }
      if (s.half > 0) {
        s.offset = ((s.offset % s.half) + s.half) % s.half;
        track.style.transform = `translate3d(${-s.offset}px, 0, 0)`;
      }
      raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    return () => {
      cancelAnimationFrame(raf);
      ro.disconnect();
    };
  }, []);

  const s = state.current;
  return (
    <div className="space-y-5">
      <div
        className="flex flex-wrap items-center justify-center gap-1.5"
        role="group"
        aria-label="Model output type"
      >
        {OUTPUT_MODES.map((m) => (
          <button
            key={m.id}
            type="button"
            onClick={() => setMode(m.id)}
            className={cn(
              "rounded-full border px-3 py-1 text-xs font-medium transition-all duration-200",
              mode === m.id
                ? "border-primary bg-primary/10 text-foreground shadow-sm shadow-primary/20"
                : "border-white/10 text-muted-foreground hover:border-muted-foreground/40 hover:text-foreground",
            )}
          >
            {m.label}
          </button>
        ))}
      </div>
    <div
      className={cn(
        "group relative touch-pan-y overflow-hidden",
        dragging ? "cursor-grabbing" : "cursor-grab",
      )}
      onMouseEnter={() => (s.paused = true)}
      onMouseLeave={() => (s.paused = false)}
      onPointerDown={(e) => {
        s.dragging = true;
        s.dragStartX = e.clientX;
        s.dragStartOffset = s.offset;
        setDragging(true);
        e.currentTarget.setPointerCapture(e.pointerId);
      }}
      onPointerMove={(e) => {
        if (!s.dragging) return;
        s.offset = s.dragStartOffset - (e.clientX - s.dragStartX);
      }}
      onPointerUp={() => {
        s.dragging = false;
        setDragging(false);
      }}
      onPointerCancel={() => {
        s.dragging = false;
        setDragging(false);
      }}
    >
      <div
        aria-hidden
        className="pointer-events-none absolute inset-y-0 left-0 z-10 w-16 bg-gradient-to-r from-background to-transparent sm:w-28"
      />
      <div
        aria-hidden
        className="pointer-events-none absolute inset-y-0 right-0 z-10 w-16 bg-gradient-to-l from-background to-transparent sm:w-28"
      />
      <div ref={trackRef} className="flex w-max select-none">
        <IndustryRow mode={mode} />
        <IndustryRow mode={mode} ariaHidden />
      </div>
    </div>
    </div>
  );
}
